# Generated by Django 4.0.6 on 2022-08-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beginners_guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='arthor',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='thumbnail',
        ),
    ]
